Metrics/AbcSize:
  Max: 23

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 18

Style/Documentation:
  Exclude:
    - app/models/application_record.rb

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

AllCops:
  Exclude:
    - config.ru
    - Gemfile
    - Rakefile
    - bin/*
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
